spring:
  #  cache:
  #    type: simple
  application:
    name: zt-framework-rbac-system
  datasource:
    druid:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/zt_user_center?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
      username: root
      password: 12345678
  profiles:
    active: local

mybatis:
  mapper-locations: classpath*:/mapper/**.xml


logging:
  config: classpath:logback-custom.xml
  level:
    com:
      zhangzhuorui:
        framework: trace

wx:
  miniAppId: xxx
  miniSecret: yyy

unicloud:
  domain: aaa
  path: bbb
  appid: ccc

password:
  secret:
    list:
      - version: 1
        value: xxx
      - version: 2
        value: yyy
